Added tests for timing.cpp/.h
dgpalmieri/aurora pull request #23
Opened 2021-11-07 01:32 UTC by TailonR

The tests need to be reviewed

2021-11-16 03:35 UTC, dgpalmieri requested changes
If you delete `doctest.h` and `timing_test.cpp` from the `EPR/Library` directory, we should try to keep all the tests in the `EPR/Library/tests` directory as Brian mentioned.

Also, I think it's a little insane that this takes 90 seconds to run (especially without saying anything about it) - is there a way that we could bring that down to 15 seconds or so? I think that if you change from seconds to quarter seconds or 1/10th of a second in the get_time() test case (line 70) you could make the runtime significantly shorter.

I would also add some docstring style comments for the auxiliary functions - what do they do, why are they set up like they are?

I also don't understand what the point of the text files your generating are - do they just capture output? It might be good to notate that somewhere as well (perhaps in a docstring!).

2021-11-16 04:41 UTC, cinderbdt commented on EPR/Library/tests/timing_test.cpp
> +#include "../timing.h"
Agreed. Makefile uses the -L($LIB) to solve this problem.

2021-11-18 11:41 UTC, cinderbdt commented on EPR/Library/tests/timing_test.cpp
> +#include "../timing.h"
I updated the Makefile to use -iquote for this.  The cpp file should just `#include "timing.h"`

2021-11-18 11:51 UTC, cinderbdt commented on EPR/Library/tests/timing_test.cpp
> +#include "../timing.h"
I tried editing the file, but I found that there are two files of different lengths so I'm not quite sure which to keep.

2021-11-18 11:52 UTC, cinderbdt commented on EPR/Library/tests/timing_test.cpp
> + *                 Auxillary functions                 *
I fixed the spelling of this word in both tests/test_timing.cpp and test_timing.cpp, but I'm not sure which one to keep.

2021-11-30 02:56 UTC, mattp0 approved these changes

2021-11-30 03:22 UTC, dgpalmieri approved these changes

2021-12-01 05:26 UTC, merged